### ISSUE TITLE
Getting errors after installing with LunarVim

### ISSUE THREAD

**Issue by delightfulabyss** [arnarg/todotxt.nvim#7]
Hi There!

I'm using LunarVim and installed and configured your plugin, but I'm getting errors when i try to run any of the commands. I have a feeling this is something on LunarVim's end but just wanted to double-check here first.

Snapshots of my config.lua:
![image](https://user-images.githubusercontent.com/41242942/184509051-b7e1e751-bf2d-4648-b3c1-985270b423e3.png)
![image](https://user-images.githubusercontent.com/41242942/184509068-3230c6e5-59a0-4c8f-bd9a-7d067106b860.png)

Errors when I try to run the ToDoTxtCapture and ToDoTxtTasksOpen commands:
![image](https://user-images.githubusercontent.com/41242942/184509103-a46d52a7-ee0b-4b0e-b770-a75c1f97772b.png)
![image](https://user-images.githubusercontent.com/41242942/184509142-83ddebda-6569-4270-901e-df301580033e.png)

Are there any configuration steps that I might have missed that might be causing this problem?

Thanks!

**Comment by pernambucano** [comment]
same here, but I don't use LunarVim. Looking in the code, it seems that something changed in nui's api, and it can't create a split anymore.

**Comment by arnarg** [comment]
> same here, but I don't use LunarVim. Looking in the code, it seems that something changed in nui's api, and it can't create a split anymore.

It seems that you're correct. The breaking changes are in https://github.com/MunifTanjim/nui.nvim/commit/c75976e823085218aeef4f5312a8c88e7d333358.

**Comment by arnarg** [comment]
This was fixed by #8. The syntax highlighting doesn't work though which is tracked by #10
